---
title: Plantilla TyHM basada en  *arxiv* style
authors:
  - name: Juan Pablo Siracusa
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza, Argentina
    email: jpsb2013@gmail.com
  - name: Mut Mariana
    department: Department of Industrial Enginnering
    affiliation: Facultad de Ingeniería 
    location: Mendoza Argentina
    email: mutmariana04@gmail.com
  - name: Isabella Morandini Monteverdi
    department: Facultad de ingeniería
    affiliation: Universidad Nacional de Cuyo
    location: Mendoza,Argentina
    email: isa.morandini03@gmail.com
  - name: Ana Gordillo
    Department: Facultad de ingeniería
    affiliation: Facultad de Ingenieria UNCUYO
    location: Mendoza,Argentina
    email: gordilloa121@gmail.com
  - name: Genovese Luciano
    department: Facultad de Ingeniería
    affiliation: Universidad Nacional de Cuyo
    location: Mendoza, Argentina
    email: luchogenovese8@gmail.com
  - name: Raby, Tomás
    department: Facultad de Ingeniería
    affiliation: Universidad Nacional de Cuyo
    location: Mendoza, Argentina
    email: tomyraby@gmail.com
    

abstract: |
  In this document, we showcase the use of R and R studio to create, compile and run multiple file formats, such as LaTeX and MarkDown. We go over the basic commands, plotting functions, creation and management of vectors and matrices and finally, how to use "for" commands. This is accomplished by explaining the code and then showcasing an example of its use.
bibliography: references.bib
biblio-style: apa
output: rticles::arxiv_article
---

# Modulo 2
```{r}
#Con este codigo creo una lista que tiene tres variables: Tree, Age, Circumference. 
#Estas variables toman valores 35 valores
Orange
#Con este codigo graficamos la variable Circumference segun la posicion que ocupa en la tabla
plot(Orange$circumference)
#Con este codigo graficamos Age en funcion de Circumference
plot(Orange$circumference,Orange$age)
#Con este codigo obtenemos ayuda de la seccion Help donde 
#nos explica como funciona el comando Sort
?sort
#En este codigo graficamos Age en funcion de Circumference, 
#la utilidad del comando sort radica en ordenar los valores de la variable Circumference
plot(sort(Orange$circumference),Orange$age)
#La siguiente funcion crea un histograma de la variable Circumference mostrando 
#la frecuencia de aparicion de los valores
hist(Orange$circumference)
#Con este codigo creamos una tabla con 19 valores 
#de una variable llamada temperature en 
#Correspondencia con 19 valores de una variable llamada pressure
pressure
#Con este codigo graficamos la pressure en funcion de la temperature 
plot(pressure$temperature,pressure$pressure)
```

#Estructura de datos

```{r}
a <- 5
b <- -3
a+b
```
##Vectores

Un vector es una estructura de datos que almacena numeros de doble presicion

```{r}
#c significa coleccion o concatenacion
# la flecha es de asignacion de un valor a la variable mi_vector_a
mi_vector_a <- c(12,34,12,54,23,12,65,34,12,56,66)
mi_vector_b<- seq(1:16)
#seq() es para apicar una secuencia de numeros
mi_vector_a
mi_vector_b
```
## Matrices
Las matrices se parecen a los vectores pero tienen filas y columnas
Se alimentan de vectores

```{r}
# Primero colocamos el vector, luego el numero de filas con nrow 
#o el numero de columnas con ncol, y luego TRUE para ordenarlos por 
#fila y FALSE por columna. PREGUNTAR: Por que por default nos deja 4 
#columnas. Lo debe hacer porque necesita todas las columnas para 
#terminar de meter al vector. Los espacios que sobran los rellena empezando de nuevo
mi_matriz_c <- matrix(mi_vector_b,nrow=4,byrow=FALSE)
mi_matriz_c
#Para acceder a un elemento coloco el nombre de mi matriz con el 
#elemento entre corchetes mi_matriz_c[2,3]
mi_matriz_c[2,3]
```

```{r}
#Para traer la fila 4 pongo nombre matriz con numero de fila y un espacio (vacio) en la columna
mi_matriz_c[4, ]
mi_matriz_c[ ,1]
```

```{r}
#Con este comando le saco la fila 2 
mi_matriz_c[-2, ]
```

```{r}
#Con este codigo puedo contar el tiempo que tarda el programa en creae mi matriz de 100x100 
start_time <- Sys.time()

mi_vector_10000 <- seq(1:10000)
mi_matriz_100 <- matrix(mi_vector_10000,nrow=100,byrow=TRUE)
mi_matriz_100

end_time <- Sys.time()
end_time - start_time
```
Bucle de promedios de tiempo

````{verbatim}
sum1=0
for (x in 1:10) {
  start_time <- Sys.time()
mi_matriz_100 <- matrix(mi_vector_10000, nrow=100, byrow=TRUE)
end_time <- Sys.time()
sum1 <- end_time - start_time + sum1
sum1 <- sum1/10
}
print(sum1)
````
Penitencia de Gauss
:se realizó la suma de todos lor terminos del vector que tiene hasta 5522 terminos. Posteriormente se calculo el tiempo y se volvio a calcular la suma de los terminos con la tecnica de Gauss.
````{verbatim}
start_time<-Sys.time()
vecsecu <- seq(1:5522)
vecsecu <- as.vector(vecsecu)
sum <- 0
for(i in vecsecu) {
  sum <- sum + vecsecu[i]
}

end_time <- Sys.time()


vecsecu <- seq(1:5522)
vecsecu <- as.vector(vecsecu)
start_time<-Sys.time()
sum <- (vecsecu[1]+vecsecu[5522])*2761
end_time <- Sys.time()
print(sum)
end_time - start_time

````
Fibonacci
:se calculó la serie de Fibonacci hasta un número mayor a 1000000 y a la vez se calculó el tiempo el que tarda el cálculo.
````{verbatim}
start_time<-Sys.time()
a <- 0
b <- 1
next_num <- a + b
while (next_num <= 1000000) {
        a <- b
        b <- next_num
        next_num <- a + b
end_time<-Sys.time()}
next_num
end_time-start_time

````
Ordenamiento de la burbuja
:consiste en un código que nos permite oredenar una serie de números de manera sencilla y necesita hacer varias iteraciones para que quede completamente ordenado.

````{verbatim}
bubblesort <- function(v) {
itemCount <- length(v)
repeat {
hasChanged <- FALSE
itemCount <- itemCount - 1
for (i in 1:itemCount) {
            if (v[i] > v[i+1]) {
                t <- v[i]
                v[i] <- v[i+1]
                v[i+1] <- t
                hasChanged <- TRUE
            }
        }
        if (!hasChanged) break
    }
    return(v)
}

# Ejemplo de uso
v <- c(9, 8, 7, 3, 1, 100)
print(bubblesort(v))

````
Programación lineal
````{verbatim}
# Cargamos el paquete necesario
library(lpSolve)

# Matriz de la función objetivo

objetivo <- c(250000,500000)

# Matriz de las restricciones 

restricciones <- matrix(c(1,0,1,1,1,3), nrow=3, byrow=TRUE)

# Lado derecho de las restricciones 

derecho <- c(18,20,30)


# Dirección de las restricciones

direccion <- c("<=","<=","<=")

# Solución óptima 

optimo <- lp(direction = "max", 
   objective.in = objetivo,
   const.mat = restricciones,
   const.dir = direccion,
   const.rhs = derecho,
   all.int = T)

optimo
best_sol <- optimo$solution
names(best_sol) <- c("x_1", "x_2") 
print(best_sol)
````

